# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-29 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20180522_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='send_csv',
            field=models.BooleanField(default=False, help_text='Attach a CSV file'),
        ),
    ]
